# Generated by Django 5.2.13 on 2026-04-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='draft', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('fees_cents', models.PositiveIntegerField(default=0)),
                ('net_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_records', to='channels.channelaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_order_id'), name='unique_sale_record_per_channel')],
            },
        ),
    ]
