const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const http = require('http');
const { spawnSync } = require('child_process');
const { v4: uuidv4 } = require('uuid');
const { query, close } = require('../../src/db/connection');
const provider = require('../../src/inference/provider');
const { autoGenerateSellerProfiles } = require('../../src/sellers/profiles');
const { batchScoreProperties } = require('../../src/sellers/distress-score');

const ROOT = path.join(__dirname, '..', '..');

function runNodeScript(scriptPath, args = []) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    cwd: ROOT,
    encoding: 'utf8',
    env: process.env
  });
}

async function resetTables() {
  await query(`
    TRUNCATE
      buyer_purchases,
      property_documents,
      property_import_records,
      wiki_promotion_queue,
      property_groups,
      entity_relationships,
      deals,
      matches,
      seller_profiles,
      buyer_profiles,
      knowledge_entries,
      properties,
      entities
    RESTART IDENTITY CASCADE
  `);
}

async function requestJson(app, method, routePath, body = undefined) {
  const server = http.createServer(app);

  await new Promise((resolve) => {
    server.listen(0, '127.0.0.1', resolve);
  });

  const { port } = server.address();

  try {
    const headers = body ? { 'content-type': 'application/json' } : {};

    if (process.env.ADMIN_API_KEY) {
      headers['x-api-key'] = process.env.ADMIN_API_KEY;
    }

    const response = await fetch(`http://127.0.0.1:${port}${routePath}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined
    });

    return {
      status: response.status,
      body: await response.json()
    };
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
}

async function importFixtureData() {
  const importRun = runNodeScript(path.join(ROOT, 'scripts', 'imports', 'import-from-realestatetool.js'), [
    '--csv',
    path.join(ROOT, 'tests', 'fixtures', 'sample-properties.json'),
    '--limit',
    '10'
  ]);
  assert.equal(importRun.status, 0, importRun.stderr || importRun.stdout);
}

async function insertAdditionalDistressProperties() {
  const sourcePropertyResult = await query(
    `
      SELECT *
      FROM properties
      WHERE owner_name = 'MAIE JT & KT DEVELOPMENT LLC'
      LIMIT 1
    `
  );
  const sourceProperty = sourcePropertyResult.rows[0];

  for (const suffix of ['A', 'B']) {
    await query(
      `
        INSERT INTO properties (
          id,
          apn,
          address,
          city,
          state,
          zip,
          property_type,
          sq_feet,
          lot_size,
          assessed_value,
          units,
          foreclosure,
          source,
          region,
          owner_name,
          trustee_name,
          trustee_phone,
          owner_entity_id,
          trustee_entity_id,
          default_date,
          default_amount,
          loan_amount,
          ltv
        )
        VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, TRUE, $12, $13, $14, $15, $16, $17,
          $18, $19, $20, $21, $22
        )
      `,
      [
        uuidv4(),
        `MAIE-DUP-${suffix}`,
        `MAIE Portfolio ${suffix}`,
        sourceProperty.city,
        sourceProperty.state,
        sourceProperty.zip,
        sourceProperty.property_type,
        sourceProperty.sq_feet,
        sourceProperty.lot_size,
        sourceProperty.assessed_value,
        sourceProperty.units,
        sourceProperty.source,
        sourceProperty.region,
        sourceProperty.owner_name,
        sourceProperty.trustee_name,
        sourceProperty.trustee_phone,
        sourceProperty.owner_entity_id,
        sourceProperty.trustee_entity_id,
        '2025-06-01',
        250000,
        900000,
        90
      ]
    );
  }
}

test('Module 4 seller workflow works end to end', async (t) => {
  t.after(async () => {
    await close();
  });

  const originalComplete = provider.complete;

  t.after(() => {
    provider.complete = originalComplete;
  });

  const migrateRun = runNodeScript(path.join(ROOT, 'scripts', 'admin', 'migrate.js'));
  assert.equal(migrateRun.status, 0, migrateRun.stderr || migrateRun.stdout);

  await resetTables();
  await importFixtureData();

  const autoGenerated = await autoGenerateSellerProfiles();
  assert.equal(autoGenerated.created, 10);
  assert.equal(autoGenerated.existing, 0);

  const sellerCountAfterAuto = await query('SELECT COUNT(*)::int AS count FROM seller_profiles');
  assert.equal(sellerCountAfterAuto.rows[0].count, 10);

  await query('DELETE FROM seller_profiles');

  const scoringResult = await batchScoreProperties();
  assert.equal(scoringResult.scored, 10);
  assert.deepEqual(
    Object.keys(scoringResult.distribution).sort(),
    ['1', '2', '3', '4', '5']
  );

  const secondScoringResult = await batchScoreProperties();
  assert.equal(secondScoringResult.scored, 0);
  assert.equal(secondScoringResult.skipped, 10);

  const { createApp } = require('../../src/api/server');
  const app = createApp();

  const distributionResponse = await requestJson(app, 'GET', '/api/sellers/distribution');
  assert.equal(distributionResponse.status, 200);
  assert.equal(distributionResponse.body.total_properties, 10);
  assert.equal(distributionResponse.body.scored, 10);
  assert.ok(
    Object.values(distributionResponse.body.distribution).filter((value) => value > 0).length >= 2
  );

  const listResponse = await requestJson(app, 'GET', '/api/sellers?min_distress=2&sort_by=distress_level');
  assert.equal(listResponse.status, 200);
  assert.ok(listResponse.body.total > 0);

  const firstProfileResult = await query(
    `
      SELECT id, property_id
      FROM seller_profiles
      ORDER BY distress_level DESC NULLS LAST, created_at ASC
      LIMIT 1
    `
  );
  const sellerProfileId = firstProfileResult.rows[0].id;
  const propertyId = firstProfileResult.rows[0].property_id;

  const byIdResponse = await requestJson(app, 'GET', `/api/sellers/${sellerProfileId}`);
  assert.equal(byIdResponse.status, 200);

  const byPropertyResponse = await requestJson(app, 'GET', `/api/sellers/by-property/${propertyId}`);
  assert.equal(byPropertyResponse.status, 200);
  assert.equal(byPropertyResponse.body.property_id, propertyId);

  const searchResponse = await requestJson(app, 'GET', '/api/sellers/search?q=MAIE');
  assert.equal(searchResponse.status, 200);
  assert.ok(searchResponse.body.total >= 1);

  const updateResponse = await requestJson(app, 'PUT', `/api/sellers/${sellerProfileId}`, {
    sensibilities: 'Wants a discreet outreach process'
  });
  assert.equal(updateResponse.status, 200);
  assert.match(updateResponse.body.sensibilities, /Wants a discreet outreach process/);

  await insertAdditionalDistressProperties();
  const rescored = await batchScoreProperties({ rescore: true });
  assert.ok(rescored.scored >= 12);

  const distressedResponse = await requestJson(app, 'GET', '/api/sellers/distressed');
  assert.equal(distressedResponse.status, 200);
  assert.ok(distressedResponse.body.total >= 1);

  const lenderPatternsResponse = await requestJson(app, 'GET', '/api/sellers/lender-patterns');
  assert.equal(lenderPatternsResponse.status, 200);
  assert.ok(lenderPatternsResponse.body.total >= 1);

  provider.complete = async () =>
    JSON.stringify({
      motivation: 'foreclosure',
      distress_level: 4,
      likely_timeline: '30_days',
      lender_status: 'pursuing_foreclosure',
      reasoning: 'The default data and trustee assignment indicate a motivated seller.',
      approach_suggestions: ['Lead with timing certainty', 'Frame options around debt relief']
    });

  const inferResponse = await requestJson(app, 'POST', '/api/sellers/infer?limit=2');
  assert.equal(inferResponse.status, 201);
  assert.equal(inferResponse.body.processed, 2);

  const inferredProfilesResult = await query(
    `
      SELECT COUNT(*)::int AS count
      FROM seller_profiles
      WHERE inferred_at IS NOT NULL
    `
  );
  assert.equal(inferredProfilesResult.rows[0].count, 2);
});
