# Generated by Django 5.2.13 on 2026-04-16 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_sku', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('set', 'Set'), ('part', 'Part'), ('minifig', 'Minifig'), ('accessory', 'Accessory'), ('mixed_lot', 'Mixed Lot'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bricklink_item_type', models.CharField(blank=True, max_length=32)),
                ('bricklink_item_number', models.CharField(blank=True, max_length=64)),
                ('bricklink_color_id', models.CharField(blank=True, max_length=32)),
                ('condition', models.CharField(blank=True, max_length=32)),
                ('completeness', models.CharField(blank=True, max_length=32)),
                ('sealed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['internal_sku'],
                'indexes': [models.Index(fields=['kind', 'active'], name='catalog_cat_kind_6c4b21_idx'), models.Index(fields=['bricklink_item_type', 'bricklink_item_number'], name='catalog_cat_brickli_61f479_idx')],
            },
        ),
    ]
