# Generated by Django 5.2.13 on 2026-04-16 00:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('acquired_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extended_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='catalog.catalogitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='inventory.inventorylocation')),
                ('purchase_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lot', to='purchasing.purchaseline')),
            ],
            options={
                'ordering': ['-received_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_key', models.CharField(max_length=128, unique=True)),
                ('reserved_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='catalog.catalogitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='inventory.inventorylot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('received', 'Received'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('adjusted', 'Adjusted'), ('transferred', 'Transferred'), ('counted', 'Counted')], max_length=24)),
                ('quantity_delta', models.IntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_events', to='catalog.catalogitem')),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='purchasing.purchaseline')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='inventory.inventorylot')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='inventory.inventoryreservation')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['item', 'received_at'], name='inventory_i_item_id_98f554_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['location', 'received_at'], name='inventory_i_locatio_540393_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['item', 'status'], name='inventory_i_item_id_4b688d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['lot', 'status'], name='inventory_i_lot_id_d76efa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['item', 'occurred_at'], name='inventory_i_item_id_ee0445_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['lot', 'occurred_at'], name='inventory_i_lot_id_b9e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='inventory_i_event_t_f8dff9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_63066e_idx'),
        ),
    ]
